from github import Github, GithubException
from typing import Dict
import logging

logger = logging.getLogger(__name__)


class Packager:
    """
    Packages generated code and creates GitHub repository
    """
    
    def create_github_repo(self, project_name: str, files: Dict[str, str], user) -> str:
        """
        Create GitHub repository and commit files
        
        Args:
            project_name: Name of the project
            files: Dictionary of file paths to contents
            user: Django user object
            
        Returns:
            GitHub repository URL
        """
        try:
            # Get GitHub token from session
            from django.contrib.sessions.models import Session
            
            github_token = None
            for session in Session.objects.all():
                data = session.get_decoded()
                if data.get('_auth_user_id') == str(user.id):
                    github_token = data.get('github_token')
                    break
            
            if not github_token:
                raise ValueError("GitHub token not found. Please reconnect your GitHub account.")
            
            # Initialize GitHub client
            g = Github(github_token)
            github_user = g.get_user()
            
            # Create repository
            repo_name = project_name.lower().replace(' ', '-')
            
            try:
                repo = github_user.create_repo(
                    name=repo_name,
                    description=f"Generated by WebForge.ai",
                    private=False,
                    auto_init=False
                )
                logger.info(f"Created repository: {repo.html_url}")
            except GithubException as e:
                if e.status == 422:  # Repository already exists
                    repo_name = f"{repo_name}-{user.id}"
                    repo = github_user.create_repo(
                        name=repo_name,
                        description=f"Generated by WebForge.ai",
                        private=False,
                        auto_init=False
                    )
                else:
                    raise
            
            # Commit files
            self._commit_files(repo, files)
            
            return repo.html_url
            
        except GithubException as e:
            logger.error(f"GitHub API error: {str(e)}")
            raise Exception(f"GitHub error: {str(e)}")
        except Exception as e:
            logger.error(f"Failed to create GitHub repo: {str(e)}")
            raise
    
    def _commit_files(self, repo, files: Dict[str, str]):
        """
        Commit multiple files to repository
        
        Args:
            repo: PyGithub repository object
            files: Dictionary of file paths to contents
        """
        try:
            # Create initial commit with all files
            file_list = []
            
            for filepath, content in files.items():
                file_list.append({
                    'path': filepath,
                    'content': content
                })
            
            # Group files by directory for better organization
            directories = set()
            for filepath in files.keys():
                parts = filepath.split('/')
                if len(parts) > 1:
                    directories.add('/'.join(parts[:-1]))
            
            # Commit files in batches
            batch_size = 50
            for i in range(0, len(file_list), batch_size):
                batch = file_list[i:i + batch_size]
                
                for file_data in batch:
                    try:
                        repo.create_file(
                            path=file_data['path'],
                            message=f"Add {file_data['path']}",
                            content=file_data['content'],
                            branch="main"
                        )
                    except GithubException as e:
                        # Skip if file already exists
                        if e.status != 422:
                            logger.warning(f"Failed to create {file_data['path']}: {str(e)}")
            
            logger.info(f"Committed {len(files)} files to repository")
            
        except Exception as e:
            logger.error(f"Failed to commit files: {str(e)}")
            raise
    
    def create_zip_package(self, files: Dict[str, str]) -> bytes:
        """
        Create ZIP package of files
        
        Args:
            files: Dictionary of file paths to contents
            
        Returns:
            ZIP file as bytes
        """
        import zipfile
        import io
        
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            for filepath, content in files.items():
                zip_file.writestr(filepath, content)
        
        zip_buffer.seek(0)
        return zip_buffer.read()
    
    def prepare_deployment_config(self, project_specs: Dict) -> Dict[str, str]:
        """
        Generate deployment configuration files
        
        Args:
            project_specs: Project specifications
            
        Returns:
            Dictionary of deployment config files
        """
        configs = {}
        
        # Vercel configuration
        configs['vercel.json'] = self._generate_vercel_config(project_specs)
        
        # Netlify configuration
        configs['netlify.toml'] = self._generate_netlify_config(project_specs)
        
        # GitHub Actions workflow
        configs['.github/workflows/deploy.yml'] = self._generate_github_actions(project_specs)
        
        return configs
    
    def _generate_vercel_config(self, specs: Dict) -> str:
        """Generate vercel.json"""
        
        framework = specs['architecture']['frontend']['framework']
        
        config = {
            "version": 2,
            "builds": [
                {
                    "src": "frontend/package.json",
                    "use": "@vercel/static-build",
                    "config": {"distDir": "dist"}
                }
            ],
            "routes": [
                {"src": "/api/(.*)", "dest": "/api/$1"},
                {"src": "/(.*)", "dest": "/"}
            ]
        }
        
        import json
        return json.dumps(config, indent=2)
    
    def _generate_netlify_config(self, specs: Dict) -> str:
        """Generate netlify.toml"""
        
        return """[build]
  command = "cd frontend && npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
"""
    
    def _generate_github_actions(self, specs: Dict) -> str:
        """Generate GitHub Actions workflow"""
        
        return """name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build
      run: |
        cd frontend
        npm run build
    
    - name: Deploy
      run: echo "Add deployment steps here"
"""
